### ISSUE TITLE
Create a simple tag-value for measurements/observations associated with datasets

### ISSUE THREAD

**Issue by cmungall** [ber-data/bertron-schema#7]
Allow each dataset to be associated with any number of tag-value pairs, where the tags are optionally harmonized. This could be used for

- biogeochemical measurements (e.g. DoC)
- host taxon, if appropriate
- outputs of processing high throughput data (enriched metabolites, taxa, functions)

The value would be of type `Any`, not required. Leaving it null indicates "I have some data of this type" (or this could be a separate field). We'd encourage simple scalars at first but in future the linkml arrays work initiated by @ialarmedalien  could go in here.

The goal here is to maximize exposing the kinds of variables and measurements different projects gather. Some groups like NMDC would submit harmonized variables, e.g. with metadata elements coming from MIxS, and categorical values coming from ENVO, PO, NCBITaxon, etc. However, it's understood some projects will not be able to provide harmonized terms for everything, and that's fine. @caufieldjh's trowel could be used for ESS-DIVE data.

This could drive a simple faceted search on the portal. This would naturally look quite messy to begin with because there is so much unharmonized but I think that's actually a feature, to be able to demonstrate this.

the basic shape could be:

```yaml
observations:
- result:
    attribute:
    value:
- result:
    attribute:
    value:
```

an example of an unharmonized variable might be:

```yaml
result:
  attribute:
     name: diss. org. C
  unit: mg/L
  value: 2
```

of course this is still missing a lot of context - when was it collected, what was the assay... but it's a start and many people can provide this!

```yaml
result:
  attribute:
     term:
       id: MIXS:nnnnn
       name: diss_org_carb
  unit: mg/L
  value: 2
```

MIXS only focuses on a subset of environmental elements. I wonder if there is a broader ontology of environmental variables... in fact as part of an LDRD we are developing this https://bioportal.bioontology.org/ontologies/ECOSIM (cc @JEDameow). And we can help harmonize unharmonized variables to this schema!

We can include categorical values

```yaml
result:
  attribute:
     name: env_process
  unit: mg/L
  categorical_value:
    term:
      id: ENVO:nnnnn
      name: flood
```

We can include summary statistics from processed data that might be useful to search on, by adding a bit more structure

```yaml
result:
  attribute:
     term:
       id: PATO:0000070
       name: abundance
    entity:
      term: NCBITaxon:nnnn
      name: Desulfovibrio spp.
    value: ...
```

The nested structure here follows COMET, and allows hook points for extensibility later

**Comment by ialarmedalien** [comment]
I think the [NMDC AttributeValue](https://microbiomedata.github.io/nmdc-schema/AttributeValue/) and its children would work well for this.

**Comment by cmungall** [comment]
@ialarmedalien great!

Just working through some examples

if the NMDC we explicitly name all the slots/attributes, so on the Entity we might have:

```yaml
tot_phosp:
  has_raw_value: "2.2 ppm"
  has_unit: ppm
  has_numeric_value: 2.2
```

If we wanted to keep this more open, we could either nest:

```yaml
attribute_values:
  - attribute: tot_phosp
     tot_phosph:
       has_raw_value: "2.2 ppm"
       has_unit: ppm
       has_numeric_value: 2.2
```

or extent the QV model so attribute is a part of it

```yaml
attribute_values:
  - attribute: tot_phosp
    has_raw_value: "2.2 ppm"
    has_unit: ppm
    has_numeric_value: 2.2
```
